# syntax = docker/dockerfile:1
# Use a minimal base image
FROM node:18-alpine AS base

# Install dependencies only when needed (Dependencies Stage)
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code (Builder Stage)
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED 1
RUN npm run build

# Production image, copy only essential files (Runner Stage)
FROM base AS runner
WORKDIR /app
ENV NODE_ENV production

# Setup Non-Root User
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# FIX: Use the standard, simplified copy logic for Next.js standalone
# 1. Copy the standalone server and its dependencies (this usually includes public assets copied by Next.js)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# 2. Copy the static assets (CSS, JS, media files generated by the build)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Note: The /public assets are often bundled into the standalone folder above. 
# We no longer need an explicit COPY /app/public ./public, as it seems to fail in your environment.

USER nextjs

EXPOSE 3000
ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["node", "server.js"]
